function init(self)
	msg.post(".", "acquire_input_focus")
	local pos = vmath.vector3(200,250,0)
	go.set_position(pos)
end


local Current = 1
function on_input(self, action_id, action)
	local Gears = {5,10,15,20,25}
	local Speed = Gears[Current]
	if action_id == hash("left") then
		local pos = go.get_position()
		pos.x = pos.x - Speed
		go.set_position(pos)
		print(pos)
	elseif action_id == hash("right") then
		local pos = go.get_position()
		pos.x = pos.x + Speed
		go.set_position(pos)
		print(pos)
	elseif action_id == hash("up") then
		local pos = go.get_position()
		pos.y = pos.y + Speed
		go.set_position(pos)
		print(pos)
	elseif action_id == hash("down") then
		local pos = go.get_position()
		pos.y = pos.y - Speed
		go.set_position(pos)
		print(pos)
	elseif action_id == hash("shift_up") then
		if action.pressed then --isolates the input / extracts only 1 input from the keyboard
			Current = Current + 1
			Speed = Gears[Current]
			pprint(Current,Speed) --added for debugging why the code wasnt working
		end
	elseif action_id == hash("shift_down") then
		if action.pressed then --isolates the input / extracts only 1 input from the keyboard
			Current = Current - 1
			Speed = Gears[Current]
			pprint(Current,Speed)
		end
	end
end